project:
    id: 1ae3f84d55a1c5cc2a1a22d1b632ee5c126d583c778bd1bf1bf20763360583ed
    name: test
    version: 1.0.0
    team: shikigami
    description: mi despliegue con fastdeploy
    organization: fastdeploy
template:
    url: https://github.com/jairoprogramador/mydeploytest.git
    ref: main
runtime:
    image:
        source: jairoprogramador/fdrunjava17azure
        tag: latest
    volumes:
        - host: $HOME/.m2/
          container: /home/fastdeploy/.m2
        - host: /var/run/docker.sock
          container: /var/run/docker.sock
    env:
        - name: ARM_CLIENT_ID
          value: '{env.AZURE_CLIENT_ID}'
        - name: ARM_CLIENT_SECRET
          value: '{env.AZURE_CLIENT_SECRET}'
        - name: ARM_TENANT_ID
          value: '{env.AZURE_TENANT_ID}'
        - name: ARM_SUBSCRIPTION_ID
          value: '{env.AZURE_SUBSCRIPTION_ID}'
state:
    backend: local
    url: ""
